services:
  # Backend API Service
  - type: web
    name: agentic-seek-backend
    env: docker
    dockerfilePath: ./Dockerfile.production
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production